name: Java CI with Gradle

on:
  push:
    branches: [ "master", "main", "dev" ]
  pull_request:
    branches: [ "master", "main", "dev" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Eclipse Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build classes
        run: ./gradlew classes
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"

      - name: Run tests and generate JaCoCo report
        run: ./gradlew test jacocoTestReport
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"

      - name: Calculate Total Coverage
        run: |
          awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print "### 📊 Total Coverage: " int(100*covered/instructions) "%" }' core/build/reports/jacoco/test/jacocoTestReport.csv >> $GITHUB_STEP_SUMMARY

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: JaCoCo-Coverage-Report
          path: core/build/reports/jacoco/test/html/
          retention-days: 30

      - name: Upload JUnit Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: JUnit-Test-Results
          path: core/build/test-results/test/TEST-*.xml
          retention-days: 30

      - name: Build Desktop Distribution
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: ./gradlew lwjgl3:dist
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"

      - name: Upload Mini-Transport-Tycoon-Build
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        with:
          name: Mini-Transport-Tycoon-Build
          path: lwjgl3/build/libs/*.jar
          retention-days: 7
